In [1]:
import numpy as np
#x=int(input("Enter the element to be searched"))
R=int(input("Enter the number of rows"))
C=int(input("Enter the number of columns"))
print("Enter the entries in a single line(separated by space):")
#User inpu of entries in a
#single line separated by space
entries=list(map(int,input().split()))
#For printing the matrix
matrix=np.array(entries).reshape(R,C)
print(matrix)

Enter the number of rows3
Enter the number of columns3
Enter the entries in a single line(separated by space):
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
def spiral_matrix( n):
        
        rowBegin=0
        rowEnd=n-1
        columnBegin=0
        columnEnd=n-1
        counter=1
        spiral=[[0 for _ in range(n)] for _ in range(n)]
        while rowBegin<=rowEnd and columnBegin<=columnEnd:
            for i in range(columnBegin,columnEnd+1):
                spiral[rowBegin][i]=counter
                counter+=1
            rowBegin+=1
            for j in range(rowBegin,rowEnd+1):
                spiral[j][columnEnd]=counter
                counter+=1
            columnEnd-=1    
            if rowBegin<=rowEnd:
                for i in range(columnEnd,columnBegin-1,-1):
                    spiral[rowEnd][i]=counter
                    counter+=1
                    
            rowEnd-=1
            if columnBegin<=columnEnd:
                for j in range(rowEnd,rowBegin-1,-1):
                    spiral[j][columnBegin]=counter
                    counter+=1
            columnBegin+=1        
        return spiral        
            

In [4]:
n=int(input())

3


In [5]:
matrix=spiral_matrix(n)
print(matrix)

[[1, 2, 3], [8, 9, 4], [7, 6, 5]]
