In [10]:
import numpy as np
#x=int(input("Enter the element to be searched"))
R=int(input("Enter the number of rows"))
C=int(input("Enter the number of columns"))
print("Enter the entries in a single line(separated by space):")
#User inpu of entries in a
#single line separated by space
entries=list(map(int,input().split()))
#For printing the matrix
matrix=np.array(entries).reshape(R,C)
print(matrix)

Enter the number of rows3
Enter the number of columns3
Enter the entries in a single line(separated by space):
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
def multi_tables(n,x):
    count=0
    for i in range(1,n+1):
        if x%i==0 and x//i<=n:
            count+=1
    return count

n=int(input("Enter the input " ))
x=int(input("Enter the number to be searched "))
count=multi_tables(n,x)
print(count)

Enter the input 4
Enter the number to be searched 12
2
